version: '3.4'

services:
  database:
    image: microsoft/mssql-server-linux
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Root123123

  mongostatistic:
    image: mongo
    ports:
    - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: statistic
      MONGO_INITDB_ROOT_PASSWORD: statisticadmin
      MONGO_INITDB_ROOT_USERNAME: statisticadmin

  mongoseneca:
      image: mongo
      ports:
      - "27018:27017"
      environment:
        MONGO_INITDB_DATABASE: seneca
        MONGO_INITDB_ROOT_PASSWORD: senecaadmin
        MONGO_INITDB_ROOT_USERNAME: senecaadmin

  datamicroservice:
    image: ${DOCKER_REGISTRY-}datamicroservice
    restart: always
    ports:
       - "8001:80"
    build:
      context: .
      dockerfile: DataMicroservice/Dockerfile
      
  apimicroservice:
    image: ${DOCKER_REGISTRY-}apimicroservice
    restart: always
    ports:
       - "8000:80"
    depends_on:
      - datamicroservice
      - database
    build:
      context: .
      dockerfile: ApiMicroservice/Dockerfile

  statisticmicroservice:
    image: ${DOCKER_REGISTRY-}statisticmicroservice
    restart: always
    ports:
       - "8002:80"
    depends_on:
      - apimicroservice
      - mongostatistic
    build:
      context: .
      dockerfile: StatisticMicroservice/Dockerfile

  senecamicroservice:
    build: ./SenecaMicroservice
    ports:
    - "3000:3000"
    command: npm start
    volumes:
    - ./SenecaMicroservice:/app
    - /app/node_modules
    depends_on:
      - apimicroservice
      - mongoseneca
  
  expressmicroservice:
    build: ./ExpressMicroservice
    ports:
      - "3002:3002"
    command: npm start
    volumes:
      - ./ExpressMicroservice:/app
      - /app/node_modules
    depends_on:
      - statisticmicroservice
      - senecamicroservice
    
  dashboardmicroservice:
      build:
        context: ./DashboardMicroservice
        args:
          - NODE_ENV=development
      ports:
        - "1233:1233"
        - "1234:1234"
        - "3010:3001"
        - "38771:38771"
      command: npm run start:dev
      volumes:
        - ./DashboardMicroservice:/app
        - /app/node_modules
      environment:
        - NODE_ENV=development
        - SENECA_MICRO=http://localhost:3000
        - STATISTIC_MICRO=http://localhost:8002
      depends_on:
        - expressmicroservice
        - statisticmicroservice
        - senecamicroservice